# Generated by Django 2.2.7 on 2019-12-15 12:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('family', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('noise_level', models.CharField(max_length=20)),
                ('fire_rate', models.CharField(max_length=10)),
                ('accuracy', models.CharField(max_length=10)),
                ('magazine_size', models.CharField(max_length=10)),
                ('max_ammo', models.CharField(max_length=10)),
                ('reload_time', models.CharField(max_length=10)),
                ('disposition', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(max_length=100)),
                ('pattern', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
