# Generated by Django 2.2.7 on 2019-12-15 12:15

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warframes', '0001_initial'),
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('family', models.CharField(max_length=20)),
                ('polarity', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('base_drain', models.IntegerField()),
                ('fusion_limit', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('property', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ModBox',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('modboxs', django_mysql.models.JSONField(default=dict)),
                ('type', models.CharField(max_length=20)),
                ('share_time', models.DateTimeField(auto_now_add=True)),
                ('warframe', models.ForeignKey(db_column='warframe_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='warframes.Warframe', to_field='name')),
                ('weapon', models.ForeignKey(db_column='weapon_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon', to_field='name')),
            ],
            options={
                'ordering': ['-share_time'],
            },
        ),
    ]
