# Generated by Django 2.2.7 on 2019-12-15 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riven_name', models.CharField(max_length=40)),
                ('properties', django_mysql.models.JSONField(default=dict)),
                ('price', models.IntegerField(default=0)),
                ('is_sell', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
    ]
