# Generated by Django 2.2.7 on 2019-12-16 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rivenmygoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riven',
            name='collector',
            field=models.ManyToManyField(related_name='collector_wfuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
