"""
Django settings for wFocus project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd+olu86!+hs!9c8+9g!boji0bflq^e8ij%(g^t-bgt-pdort*p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
]

#  debug_toolbar扩展配置
INTERNAL_IPS = [
    '127.0.0.1',
]
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',  # django版本
    'debug_toolbar.panels.timer.TimerPanel',  # 页面加载用时
    'debug_toolbar.panels.settings.SettingsPanel',  # settings配置信息
    'debug_toolbar.panels.headers.HeadersPanel',  # 当前请求头与响应头信息
    'debug_toolbar.panels.request.RequestPanel',  # 当前请求相关信息，包括：视图函数，Cookie，Session等
    'debug_toolbar.panels.sql.SQLPanel',  # 执行的SQL语句
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',  # 加载的静态文件
    'debug_toolbar.panels.templates.TemplatesPanel',  # 模板信息
    'debug_toolbar.panels.cache.CachePanel',  # 缓存信息
    # 'debug_toolbar.panels.signals.SignalsPanel',  # 信号
    # 'debug_toolbar.panels.logging.LoggingPanel',  # 日志信息
    # 'debug_toolbar.panels.redirects.RedirectsPanel',  # 重定向信息
    # 'debug_toolbar.panels.profiling.ProfilingPanel',  # 分析信息
]
DEBUG_TOOLBAR_CONFIG = {

}

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方扩展
    'rest_framework',
    'django_mysql',
    'debug_toolbar',

    # 安装创建的app
    'apps.index',
    'apps.cms',
    'apps.wfusers',
    'apps.home',
    'apps.alerts',
    'apps.warframes',
    'apps.mods',
    'apps.crawlers',
    'apps.weapons',
    'apps.translation',

    'apps.rivenmygoods',
    'apps.rivenmarket',
    'apps.msgs',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # debug工具中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.wfusers.middlewares.request_permissions_middleware'  # 自定义中间件
]

ROOT_URLCONF = 'wFocus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web', 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'wFocus.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'warframe',
        'USER': 'tuffy',
        'PASSWORD': 'sy14213ZM',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            # 告诉mysql使用的是'utf8mb4'
            'charset': 'utf8mb4',
        },
        # 告诉Django使用的是 'utf8mb4'
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'wfusers.WfUser'

# 配置缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
# 配置session存储方式
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'web', 'dist'),
    os.path.join(BASE_DIR, 'web', 'src'),  # 后期要删掉
]

# 媒体文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




