# Generated by Django 2.2.7 on 2019-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_key', models.CharField(max_length=50)),
                ('zh_value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
