# Generated by Django 2.2.7 on 2019-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('health', models.IntegerField()),
                ('shield', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('power', models.IntegerField()),
                ('sprint_speed', models.FloatField()),
                ('power_strength', models.FloatField(default=1)),
                ('power_duration', models.FloatField(default=1)),
                ('power_range', models.FloatField(default=1)),
                ('power_efficiency', models.FloatField(default=1)),
                ('img', models.URLField(max_length=255, null=True)),
            ],
        ),
    ]
